export const CLARITY_CONFIG = {
  baseUrl: 'https://www.clarity.ms/export-data/api/v1/project-live-insights',
  projectId: process.env.CLARITY_PROJECT_ID || 'unknown',
  heatmapBaseUrl: 'https://clarity.microsoft.com/projects',
  maxCallsPerDay: 10,
  maxRows: 1000,
  maxDays: 3 as const,
  dimensions: [
    'Browser',
    'Device',
    'Country',
    'OS',
    'Source',
    'Medium',
    'Campaign',
    'Channel',
    'URL',
  ] as const,
  metrics: [
    'Traffic',
    'ScrollDepth',
    'EngagementTime',
    'DeadClickCount',
    'RageClickCount',
    'ExcessiveScroll',
    'QuickbackClick',
    'ScriptErrorCount',
    'ErrorClickCount',
  ] as const,
  severityThresholds: {
    critical: { rageClicks: 50 },
    high: { rageClicks: 20, abandonmentRate: 0.3 },
    medium: { rageClicks: 10 },
    low: { rageClicks: 0 },
  },
} as const;
